app:
  tokens-ms:
    url: http://tokens-service:7000/
    refresh-token-url: auth/token/refresh
    access-token-url: auth/token/access

spring:
  cloud:
    gateway:
      routes:
        - id: identity
          uri: http://identity-service:7000/
          predicates:
            - Path=/identity/**
          filters:
            - RemoveRequestHeader=Bearer

        - id: order
          uri: http://order-service:7000/
          predicates:
            - Path=/order/**
          filters:
            - RemoveRequestHeader=Bearer

        - id: tokens
          uri: http://tokens-service:7000/
          predicates:
            - Path=/auth/**

application:
  cors:
    allowedOrigins: "*"
    allowedHeaders: "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
