spring:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  jackson:
    visibility:
      field: any

  liquibase:
    change-log: classpath:migration/changelog/db.changelog.master.xml

logging:
  level:
    liquibase: INFO
